global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'query-service'
    static_configs:
      - targets: ['query-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s
